---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque

# mongo-user & mongo-password must be in Base64 encode.
# We can covert our username & password to Base64 encode using online convertor.
# mongouser to Base64 Encode = bW9uZ291c2Vy
# mongopassword to Base64 Encode = bW9uZ29wYXNzd29yZA==
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==